version: "3.8"

networks:
  network_sonar:

services:
  postgres:
    image: postgres
    container_name: Postgres
    environment:
      POSTGRES_PASSWORD: sonar
      POSTGRES_USER: sonar
      POSTGRES_DB: sonar
    volumes:
      - /YourFouder/Postgres/Data:/var/lib/postgresql/data
      - /YourFouder/Postgres/Config:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - network_sonar
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

  sonarqube:
    image: sonarqube
    container_name: SonarQube
    environment:
      sonar.jdbc.username: sonar
      sonar.jdbc.password: sonar
      sonar.jdbc.url: jdbc:postgresql://postgres/sonar
    volumes:
      - /YourFouder/SonarQube/data:/opt/SonarQube/data
      - /YourFouder/SonarQube/logs:/opt/SonarQube/logs
      - /YourFouder/SonarQube/extensions:/opt/SonarQube/extensions
      - /YourFouder/SonarQube/plugins:/opt/sonarqube/lib/bundled-plugins
    ports:
      - "9000:9000"
    networks:
      - network_sonar
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 768M

  sonar-scanner:
    image: sonarsource/sonar-scanner-cli:latest
    container_name: SonarScanner
    volumes:
      - /YourFouder/Scanner:/opt/sonar/scanner/workspace
    networks:
      - network_sonar
    depends_on:
      - sonarqube
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
