version: "3.9"

networks:
  sonar_network:

services:
  postgres:
    image: postgres
    container_name: Postgres
    environment:
      POSTGRES_PASSWORD: sonar
      POSTGRES_USER: sonar
      POSTGRES_BD: sonar
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - sonar_network

  sonarqube:
    image: sonarqube
    container_name: SonarQube
    environment:
      sonar.jdbc.username: sonar
      sonar.jdbc.password: sonar
      sonar.jdbc.url: jdbc:postgresql://postgres/sonar
    volumes:
      - SonarQube-conf:/opt/sonarqube/data
      - sonarqube-conf:/opt/sonarqube/logs
      - sonarqube-conf:/opt/sonarqube/extensions
    ports:
      - "9000:9000"
    networks:
      - sonar_network

volumes:
  pgdata:
  SonarQube-conf:
  sonarqube-conf: